RF: use pytest for running tests

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -20,16 +20,18 @@ MIN_CYTHONVER = 0.24
 CYTHON_VER := $(shell dpkg -l cython 2>/dev/null | awk '/^ii/{print $$3;}' || echo 0)
 RECONF = $(shell dpkg --compare-versions $(CYTHON_VER) ge $(MIN_CYTHONVER) && echo ",autoreconf" || echo "")
 
-# Some tests are known to fail randomly so need to be excluded ATM
-# A bit aggressive exclusion of some tests which exhibit a problem I have no time to deal with on arm64
-NOSEARGS := $(shell dpkg --print-architecture | grep -q -v arm64 || echo --exclude='test_dump')
-# https://github.com/scikit-learn/scikit-learn/issues/7544
-NOSEARGS += $(shell dpkg --print-architecture | grep -q -v i386 || echo --exclude='test_gpr')
-# https://github.com/scikit-learn/scikit-learn/issues/7572
-NOSEARGS += $(shell dpkg --print-architecture | grep -q -v armel || echo --exclude='test_matthews_corrcoef')
-# --exclude='test_(sparse_svc_clone_with_callable_kernel|spectral_clustering_sparse|ovr_fit_predict)'
-# https://buildd.debian.org/status/fetch.php?pkg=scikit-learn&arch=ppc64el&ver=0.18-3&stamp=1475603905
-NOSEARGS += $(shell dpkg --print-architecture | grep -q -v ppc64el || echo --exclude='test_non_meta_estimators')
+NOSEARGS :=
+# TODO: figure out how to transfer to pytests specification if still relevant
+# # Some tests are known to fail randomly so need to be excluded ATM
+# # A bit aggressive exclusion of some tests which exhibit a problem I have no time to deal with on arm64
+# NOSEARGS := $(shell dpkg --print-architecture | grep -q -v arm64 || echo --exclude='test_dump')
+# # https://github.com/scikit-learn/scikit-learn/issues/7544
+# NOSEARGS += $(shell dpkg --print-architecture | grep -q -v i386 || echo --exclude='test_gpr')
+# # https://github.com/scikit-learn/scikit-learn/issues/7572
+# NOSEARGS += $(shell dpkg --print-architecture | grep -q -v armel || echo --exclude='test_matthews_corrcoef')
+# # --exclude='test_(sparse_svc_clone_with_callable_kernel|spectral_clustering_sparse|ovr_fit_predict)'
+# # https://buildd.debian.org/status/fetch.php?pkg=scikit-learn&arch=ppc64el&ver=0.18-3&stamp=1475603905
+# NOSEARGS += $(shell dpkg --print-architecture | grep -q -v ppc64el || echo --exclude='test_non_meta_estimators')
 
 
 # try to prevent unsunctioned downloads
@@ -90,8 +92,8 @@ ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
 	export PYTHONPATH=`/bin/ls -d $$PWD/debian/tmp/usr/lib/python$$PY/*/`; \
 	export MPLCONFIGDIR=$(CURDIR)/build HOME=$(CURDIR)/build; \
 	export JOBLIB_MULTIPROCESSING=2; \
-	cd build/; python$* /usr/bin/nosetests -s -v $(NOSEARGS) sklearn && \
-	  { python$* /usr/bin/nosetests -v --with-doctest --doctest-extension=rst ../doc/ || : ; } # doctests are failing ATM
+	cd build/; python$* -m pytest -s -v $(NOSEARGS) $$PYTHONPATH/sklearn 
+    # && { python$* /usr/bin/nosetests -v --with-doctest --doctest-extension=rst ../doc/ || : ; } # doctests are failing ATM
 else
 	: # Skip unittests due to nocheck
 endif
